server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ivan-calzada/ms-application-properties
          username: 
          password: 
          default-label: cicb_17042022
          search-paths: 
          - api-disquera
